### ISSUE TITLE
Center heading text.

### ISSUE THREAD

**Issue by josephtkim** [lunnie82/prj-rev-bwfs-dasmoto#2]
One small styling property that seemed to be missing is the centered text for the heading. To do this, add the property in CSS,

```css
h1 {
  text-align: center;
}
```
